import type { Metadata } from 'next'
import { Playfair, Inter } from 'next/font/google'
import '../styles/globals.css'
import { css, cx } from '@styled-system/css'
import Layout from '@/components/layout/Layout'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

const playfair = Playfair({
  variable: '--font-playfair',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          `${playfair.variable} ${inter.variable}`,
          css({ bg: 'secondary.500' })
        )}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
