import type { Metadata } from 'next'
import { Playfair, Inter } from 'next/font/google'
import '../styles/globals.css'
import LayoutSidebar from '@/components/layout/LayoutSidebar'
import { css, cx } from '@styled-system/css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

const playfair = Playfair({
  variable: '--font-playfair',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cx(`${playfair.variable} ${inter.variable}`)}>
        <main
          className={css({
            width: '100%',
            minHeight: '100%',
            lg: {
              paddingRight: '270px'
            }
          })}
        >
          {children}
        </main>
        <LayoutSidebar />
      </body>
    </html>
  )
}
