import type { Metadata } from 'next'
import { Playfair, Inter } from 'next/font/google'
import '@/styles/globals.css'
import { css, cx } from '@styled-system/css'
import Layout from '@/components/layout/Layout'
import { Locale } from '@/i18n/locales'
import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

const playfair = Playfair({
  variable: '--font-playfair',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: Locale }>
}>) {
  const locale = (await params).locale
  const translations = await getMessages({ locale })

  return (
    <html lang={locale}>
      <body
        className={cx(
          `${playfair.variable} ${inter.variable}`,
          css({ bg: 'secondary.500' })
        )}
      >
        <NextIntlClientProvider messages={translations}>
          <Layout>{children}</Layout>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
